{
    "CVE_data_meta": {
        "ASSIGNER": "psirt@us.ibm.com",
        "DATE_PUBLIC": "2019-06-27T00:00:00",
        "ID": "CVE-2019-4101",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "10.5"
                                },
                                {
                                    "version_value": "10.1"
                                },
                                {
                                    "version_value": "11.1"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "IBM"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 10.1, 10.5, and 11.1 is vulnerable to a denial of service. Users that have both EXECUTE on PD_GET_DIAG_HIST and access to the diagnostic directory on the DB2 server can cause the instance to crash. IBM X-Force ID: 158091."
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "BM": {
                        "A": "H",
                        "AC": "L",
                        "AV": "L",
                        "C": "N",
                        "I": "N",
                        "PR": "N",
                        "S": "U",
                        "SCORE": "6.200",
                        "UI": "N"
                    },
                    "TM": {
                        "E": "U",
                        "RC": "C",
                        "RL": "O"
                    }
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "Denial of Service",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://www.ibm.com/support/docview.wss?uid=ibm10880741",
                "refsource": "CONFIRM",
                "url": "https://www.ibm.com/support/docview.wss?uid=ibm10880741"
            },
            {
                "name": "ibm-db2-cve20194101-dos (158091)",
                "refsource": "XF",
                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/158091"
            },
            {
                "name": "109021",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/109021"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}