{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-15486",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1",
                "refsource": "MISC",
                "url": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1"
            },
            {
                "name": "https://github.com/ierror/django-js-reverse/pull/81",
                "refsource": "MISC",
                "url": "https://github.com/ierror/django-js-reverse/pull/81"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}