{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2018-10322",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "The xfs_dinode_verify function in fs/xfs/libxfs/xfs_inode_buf.c in the Linux kernel through 4.16.3 allows local users to cause a denial of service (xfs_ilock_attr_map_shared invalid pointer dereference) via a crafted xfs image."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "RHSA-2018:3083",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2018:3083"
            },
            {
                "name": "https://www.spinics.net/lists/linux-xfs/msg17215.html",
                "refsource": "MISC",
                "url": "https://www.spinics.net/lists/linux-xfs/msg17215.html"
            },
            {
                "name": "RHSA-2018:2948",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2018:2948"
            },
            {
                "name": "103960",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/103960"
            },
            {
                "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199377",
                "refsource": "MISC",
                "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199377"
            },
            {
                "name": "RHSA-2018:3096",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2018:3096"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}