{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2007-6740",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "The ftp_STOU function in FTPServer.py in pyftpdlib before 0.2.0 does not limit the number of attempts to discover a unique filename, which might allow remote authenticated users to cause a denial of service via a STOU command."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn37&r=37&format=side&path=/trunk/pyftpdlib/FTPServer.py",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn37&r=37&format=side&path=/trunk/pyftpdlib/FTPServer.py"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/source/detail?r=37",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/detail?r=37"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/issues/detail?id=25",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=25"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}