{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2008-6547",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "schema.py in FormEncode for Python (python-formencode) 1.0 does not apply the chained_validators feature, which allows attackers to bypass intended access restrictions via unknown vectors."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "30282",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/30282"
            },
            {
                "name": "FEDORA-2008-6312",
                "refsource": "FEDORA",
                "url": "https://www.redhat.com/archives/fedora-package-announce/2008-July/msg00607.html"
            },
            {
                "name": "http://sourceforge.net/tracker/index.php?func=detail&aid=1925164&group_id=91231&atid=596416",
                "refsource": "CONFIRM",
                "url": "http://sourceforge.net/tracker/index.php?func=detail&aid=1925164&group_id=91231&atid=596416"
            },
            {
                "name": "formencode-chainedvalidators-sec-bypass(43878)",
                "refsource": "XF",
                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/43878"
            },
            {
                "name": "47082",
                "refsource": "OSVDB",
                "url": "http://osvdb.org/47082"
            },
            {
                "name": "31163",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/31163"
            },
            {
                "name": "http://sourceforge.net/tracker/download.php?group_id=91231&atid=596416&file_id=271779&aid=1925164",
                "refsource": "CONFIRM",
                "url": "http://sourceforge.net/tracker/download.php?group_id=91231&atid=596416&file_id=271779&aid=1925164"
            },
            {
                "name": "31081",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/31081"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}