{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2018-16878",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "affects up to and including version 2.0.1"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "ClusterLabs"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "A flaw was found in pacemaker up to and including version 2.0.1. An insufficient verification inflicted preference of uncontrolled processes can lead to DoS"
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "vectorString": "6.2/CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "version": "3.0"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-400",
                        "description": "CWE-400",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16878",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16878"
            },
            {
                "name": "https://github.com/ClusterLabs/pacemaker/pull/1749",
                "refsource": "CONFIRM",
                "url": "https://github.com/ClusterLabs/pacemaker/pull/1749"
            },
            {
                "name": "108039",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/108039"
            },
            {
                "name": "USN-3952-1",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3952-1/"
            },
            {
                "name": "FEDORA-2019-e4c8de3fb7",
                "refsource": "FEDORA",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HR6QUYGML735EI3HEEHYRDW7EG73BUH2/"
            },
            {
                "name": "FEDORA-2019-e71f6f36ac",
                "refsource": "FEDORA",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3GCWFO7GL6MBU6C4BGFO3P6L77DIBBF3/"
            },
            {
                "name": "FEDORA-2019-b502250ba4",
                "refsource": "FEDORA",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FY4M4RMIG2POKC6OOFQODGKPRYXHET2F/"
            },
            {
                "name": "openSUSE-SU-2019:1342",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00012.html"
            },
            {
                "name": "openSUSE-SU-2019:1400",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00034.html"
            },
            {
                "name": "RHSA-2019:1278",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:1278"
            },
            {
                "name": "RHSA-2019:1279",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:1279"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}